spring:
  application:
    name: technical-base-point
  datasource:
    url: jdbc:postgresql://192.168.10.128:5432/postgres?autosave=conservative
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver


#mybatis配置
mybatis:
  config-location: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-generated-keys: true
